### ISSUE TITLE
Temperature Sensor functionality test

### ISSUE THREAD

**Issue by DivyeshShashikant** [cu-ecen-aeld/final-project-DivyeshShashikant#1]
**DoD:**

- [x]  Temperature Sensor (TMP102) functions correctly and outputs correct temperature readings.

**Task**

- [x] check against already developed code for i2c temperature sensor (TMP102) on FRDM KL25Z and check if the sensor is functioning correctly. 
- [x] verify temperature values in correct range and see if it does not have extreme offset.

**Blockers**
- [x] Source TMP102 (temperature sensor)

**Comment by DivyeshShashikant** [comment]
I used the already compiled code to test the Temperature Sensor (TMP102) on the FRDM KL25Z development board in order to check its functionality. After interfacing the sensor with the board I was able to get correct readings of temperature from the sensor. Also, verifying it with the ambient temperature I was getting nearly accurate temperature values. Thus, this helped me check that the sensor was working fine. Below listed are a range of values which will define the respective states of degree of temperature readings. 

| Temperature Range (°C) |  	State  	    |
|------------------------|------------------|
|     	 0-15      	 |       Cool	    |
|     	16-26     	 |       Pleasant   | 
|     	27-35     	 |       Warm       | 
|     	36-50     	 |        Hot	    |
|     	 >50      	 |      Too Hot	    |

Below are the temperature reading screenshots

![TMP102](https://user-images.githubusercontent.com/89857734/162653732-7a7a4772-ff33-4f6e-81f4-f04ac0ac4c00.PNG)
![pleassant_temp](https://user-images.githubusercontent.com/89857734/162653735-0efb5e2d-e900-46f1-8152-814318935f18.PNG)
