### ISSUE TITLE
Detect Temperature Sensor on BeagleBone Black

### ISSUE THREAD

**Issue by DivyeshShashikant** [cu-ecen-aeld/final-project-DivyeshShashikant#2]
**DoD:**

- [x]  Detect i2c temperature sensor (TMP102) on the i2c bus of beaglebone black.

**Task**

- [x] use command i2cdetect -l to list all the available i2c buses on the BBB board.
- [x] use command i2cdetect -r -y N to list the slave device address on the N channel i2c of the BBB board.
- [x] use command i2cset -y N (device address) (device register) to write the slave device's register on selected N i2c channel.
- [x] use command i2cdump -y N (device address) to read the slave device's register on selected N i2c channel.

**Blockers**
- [x] [SSH access not configured to check I2C bus detection](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/issues/3)

**Comment by DivyeshShashikant** [comment]
1. Could not implement the above mentioned tasks due to the [blocker](https://github.com/cu-ecen-aeld/final-project-ruchitnaik/issues/3) faced. 
2. Post creating the buildroot image and flashing it onto the BBB board, we were expecting to log in via SSH over the USB interface. Unfortunately, we were not able to login.

**Comment by DivyeshShashikant** [comment]
After the i2c patch was applied and upon running the the commands **i2cdetect -l** and **ls /dev/ | grep i2c** on the BBB board, I noticed the i2c buses (0,1,2) respectively.
![i2cdev_patch_added_successful](https://user-images.githubusercontent.com/89857734/162656072-5b2aa70b-7427-47ae-9985-0c5d5f8946d6.PNG)
![i2cdetect_l](https://user-images.githubusercontent.com/89857734/162656101-75ad993f-b346-4ca4-a1a8-15ad5fe643ac.png)

**Comment by DivyeshShashikant** [comment]
ran the command **i2cdetect -r -y 2** to list the slave device (TMP102) address (0x48) on the 2nd channel i2c of the BBB board. The outputs are before and after connecting the sensor to the BBB board.
![sensor_detect](https://user-images.githubusercontent.com/89857734/162656453-8dd64cef-776d-4f67-91d5-5086ca18cae1.PNG)

**Comment by DivyeshShashikant** [comment]
executed the command **i2cset -y 2 0x48 0x00** The first hex number is the i2c device address followed by the specific data register to be written. I verified the write transactions on a logic analyzer and found it to be correct.
![logic_i2cset](https://user-images.githubusercontent.com/89857734/162656938-f2f684c7-1978-407a-a997-85a96b4494e9.PNG)

**Comment by DivyeshShashikant** [comment]
executed the command **i2cdump -y 2 0x48 w** to read raw temperature values. The first hex number is the i2c device address followed by the specific data register to be written. I verified the read transactions on a logic analyzer and found it to be correct. The first column values are the required values of out which 12 bits shall be the temperature readings. Further operations will be done on these values to get the temperature in a readable form.
![logc_i2chexdump](https://user-images.githubusercontent.com/89857734/162658200-7e9d7f7e-0a90-4b15-8e39-cd8b0a7991a9.PNG)
