### ISSUE TITLE
I2C temperature sensor integration with BBB board

### ISSUE THREAD

**Issue by DivyeshShashikant** [cu-ecen-aeld/final-project-DivyeshShashikant#3]
**DoD**
- [x] Implementing code to get temperature readings from the temperature sensor (TMP102)

**Tasks**

- [x] Code to get temperature readings from the sensor.
- [x] Cross compile sensor test code for target BBB and install it in /usr/bin.
- [x] Display the temperature readings on the BBB terminal.

**Blockers**
No blockers identified.

**Comment by DivyeshShashikant** [comment]
For the sprint 2, I wrote the code to read temperature sensor (TMP102) readings on the i2c bus 2 of the BBB board. For reference I used [link](https://www.kernel.org/doc/Documentation/i2c/dev-interface) for the development of my code. I then was able to successfully cross compile the code and install it in the target/usr/bin. 

Sensor Test [Code](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/blob/master/TMP102test/tmp102.c)
![usr-dev-present](https://user-images.githubusercontent.com/89857734/162671026-21622baf-a070-49fd-9e21-73d22a0e0ea2.png)
![app_cross-comp-vers](https://user-images.githubusercontent.com/89857734/162671798-bc927762-4a09-4e34-8971-50190ff9fe70.png)

**Comment by DivyeshShashikant** [comment]
On running the tmp102 executable, I was getting the current temperature readings. I took the sensor outside so as to get some low temperature values and then bringing back the sensor in raised the temperature readings. 
![cross-compiled-readings](https://user-images.githubusercontent.com/89857734/162671660-2fa47cfb-55a5-46d5-96e7-e79d4e6f78bc.png)
