### ISSUE TITLE
Socket Program on Beagle Bone Black

### ISSUE THREAD

**Issue by DivyeshShashikant** [cu-ecen-aeld/final-project-DivyeshShashikant#4]
**DoD:**

- [x]  Implement the socket server program on BBB board which will send the temperature values to the client over TCP socket

**Task**

- [x] develop server code to be implemented on the BBB board.
- [x] check if server code binds to a specific port.
- [x] listening on the port to see if any client wants to connect.
- [x] check if server-client connection is established.
- [x] integrate [sensor test code](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/blob/master/TMP102test/tmp102.c) (TMP102 code) with the server code.
- [x] send temperature data to client.

**Blockers**
None identified at the moment.

**Comment by DivyeshShashikant** [comment]
For the sprint 3, I wrote the [server](https://github.com/cu-ecen-aeld/final-project-DivyeshShashikant/blob/master/Server_BBB/server.c) code to send temperature sensor (TMP102) readings on the i2c bus 2 of the BBB board to the client via TCP socket. For reference, I used the Assignment-5 code. Initially, the server listens on the specified port for any incoming client connections. After connecting to the client, the temperature readings shall be sent to the client only if valid commands are received on the server (BBB) end. The client has both the option to retrieve values in Celsius or Fahrenheit. The server displays values in both units but only sends the required reading units.  

- server listening on port 3457 for incoming client connection
![Screenshot from 2022-04-17 19-36-54](https://user-images.githubusercontent.com/89857734/163750887-82ee3dce-aa0c-4fd6-a49f-19270bf23a9f.png)

- server connecting to client
![Screenshot from 2022-04-17 19-36-09](https://user-images.githubusercontent.com/89857734/163750963-f048eeda-7d51-4234-8765-0dae70d5673e.png)

- Commands from client are intercepted by the server.
![image](https://user-images.githubusercontent.com/89857734/163754977-9398bb41-dd1b-422d-aaf4-2ffeac439101.png)


- server responds to the client commands, sends celsius readings on READC and fahrenheit readings on READF respectively
![Screenshot from 2022-04-17 19-40-41](https://user-images.githubusercontent.com/89857734/163753238-14addbde-1450-4ffe-bdc9-17c3d0e9ec72.png)

- client commands
![Client_Integrate_BBB](https://user-images.githubusercontent.com/89857734/163753455-7ebb7bed-9034-414b-9c37-c91e744a2275.png)
